# Generated by Django 4.2.1 on 2023-05-09 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AEPDE_APP', '0003_alter_producto_fecha_produccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fecha_produccion',
            field=models.DateTimeField(),
        ),
    ]
