# Generated by Django 4.2.1 on 2023-05-09 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AEPDE_APP', '0004_alter_producto_fecha_produccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='cod_sucursal',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
    ]
