# Generated by Django 4.2.1 on 2023-05-09 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AEPDE_APP', '0009_alter_producto_fecha_produccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fecha_produccion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_vencimiento_prod',
            field=models.DateTimeField(),
        ),
    ]
