# Generated by Django 4.2.1 on 2023-05-10 03:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AEPDE_APP', '0012_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='nombre',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
