# Generated by Django 4.2.1 on 2023-05-11 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AEPDE_APP', '0013_sucursal_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productor',
            fields=[
                ('cod_productor', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=500)),
            ],
        ),
    ]
