# Generated by Django 4.2.1 on 2023-05-11 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AEPDE_APP', '0015_producto_cod_productor'),
    ]

    operations = [
        migrations.AddField(
            model_name='productor',
            name='correo_contacto',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productor',
            name='telefono_contacto',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
    ]
