# Generated by Django 4.2.1 on 2023-05-16 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AEPDE_APP', '0016_productor_correo_contacto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productor',
            name='cod_productor',
            field=models.IntegerField(max_length=9, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='cod_sucursal',
            field=models.IntegerField(max_length=25, primary_key=True, serialize=False),
        ),
    ]
