# Generated by Django 4.2.1 on 2023-05-16 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AEPDE_APP', '0017_alter_productor_cod_productor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productor',
            name='telefono_contacto',
            field=models.IntegerField(max_length=8),
        ),
    ]
