# Generated by Django 4.2.1 on 2023-05-19 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AEPDE_APP', '0021_carrito_itemcarrito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transportista',
            fields=[
                ('codigo_transportista', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50)),
                ('monto', models.IntegerField(default=1)),
                ('codigo_transportista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AEPDE_APP.transportista')),
            ],
        ),
    ]
