# Generated by Django 4.2.1 on 2023-05-23 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AEPDE_APP', '0023_alter_tarifa_options_oferta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oferta',
            old_name='nuevo_precio',
            new_name='precio_oferta',
        ),
    ]
