# Generated by Django 4.2.1 on 2023-05-31 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AEPDE_APP', '0024_rename_nuevo_precio_oferta_precio_oferta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=200)),
                ('detalle', models.CharField(max_length=999)),
                ('imagen', models.ImageField(null=True, upload_to='images')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AEPDE_APP.producto')),
            ],
        ),
    ]
