# Generated by Django 4.2.1 on 2023-05-31 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AEPDE_APP', '0026_alter_reclamo_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamo',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
